appShop/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]


if settings.DEBUG:
    urlpatterns += [
    path("__debug__/", include("debug_toolbar.urls")),
    ]   
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appShop/main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

appShop/orders/urls.py
from django.urls import path
from orders import views


app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
]

appShop/orders/models.py
from django.db import models
from users.models import User
from goods.models import Products
# Create your models here.

class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0




class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, verbose_name="Пользователь", blank=True, null=True, default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    requires_delivery = models.BooleanField(default=False, verbose_name='Требуется доставка')
    delivery_adress = models.TextField(null=True, blank=True, verbose_name='Адрес доставки')
    payment_on_get = models.BooleanField(default=False, verbose_name='Оплата при получении')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    status = models.CharField(max_length=50, default='В обработке', verbose_name='Статус заказа')

    class Meta:
        db_table = 'order'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
    
    def __str__(self):
        return f"Заказ № {self.pk} | Покупятеля {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, verbose_name='Продукт', null=True, default=None)
    name = models.CharField(max_length=150, verbose_name='Название')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')

    class Meta:
        db_table = "order_item"
        verbose_name = 'Проданный товар'
        verbose_name_plural = 'Проданные товвары'

    objects = OrderitemQueryset.as_manager()

    def product_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f'Товар {self.name} | Заказ № {self.order.pk}'        

appShop/orders/forms.py
import re
from django import forms


class CreateOrderForm(forms.Form):
    
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
        ('0', False),
        ('1', True),
    ],
    )
    delivery_adress = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
        ('0', "False"),
        ('1', "True"),
    ],
    )

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError('Номер телефона должен содержать только цифры')
        
        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError('Не верный формат номера ')

appShop/orders/views.py
from django.shortcuts import render, redirect
from orders.models import Order, OrderItem
from carts.models import Cart
from orders.forms import CreateOrderForm
from django.db import transaction
from django.forms import ValidationError
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here. 


@login_required
def create_order(request):
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if cart_items.exists():
                        order = Order.objects.create(
                            user = user,
                            phone_number = form.cleaned_data['phone_number'],
                            requires_delivery = form.cleaned_data['requires_delivery'],
                            delivery_adress = form.cleaned_data['delivery_adress'],
                            payment_on_get = form.cleaned_data['payment_on_get'],
                        )

                        for cart_item in cart_items:
                            product = cart_item.product
                            name = cart_item.product.name
                            price = cart_item.product.sell_price()
                            quantity = cart_item.quantity

                            if product.quantity < quantity:
                                raise ValueError(f'Недостаточно количество товаров {name} на складе\
                                                 В наличии - {product.quantity}')
                            
                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()
                        
                        cart_item.delete()

                        messages.success(request, "Заказ оформлен")
                        return redirect('main:index')
            except ValidationError as e:
                messages.success(request, str(e))
                return redirect('cart:order')
                    
    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
        }
        form = CreateOrderForm(initial=initial)
    context = {
        'title': 'Оформление заказа',
        'from': form
    }
    return render(request, 'orders/create_order.html', context=context)

appShop/orders/templates/orders/create_order.html
{% load static %}
{% load carts_tags %}						
							
{%user_carts request as carts%}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Products</title>

    


    <!--== Google Fonts ==-->
    {% comment %} <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,400i,500,500i,600,700,800,900" rel="stylesheet"> {% endcomment %}
    {% comment %} <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,500,600,700" rel="stylesheet"> {% endcomment %}

    <!--== Bootstrap CSS ==-->
    <link href="{% static 'assetsС/css/Сbootstrap.min.css' %}" rel="stylesheet" />

    <!--== Main Style CSS ==-->
    <link href="{% static 'assetsС/css/style.css' %}" rel="stylesheet" />

</head>

<body>

<!--wrapper start-->
<div class="wrapper product-information-wrapper">
  
  <main class="main-content">
    <!--== Start Product Area Wrapper ==-->
    <section class="product-area product-information-area">
      <div class="container">
        <div class="product-information">
          <div class="row">
            <div class="col-lg-7">
             

              <div class="edit-checkout-information">
                <h4 class="title">Контактная информация</h4>
                <div class="logged-in-information">
                  <div class="thumb" data-bg-img="assets/img/photos/gravatar2.png"></div>
                  <p>
                    <span class="name">{{carts.user.first_name}}</span>
                    <span>({{carts.user.email}})</span>
                    <a href="login.html">Log out</a>
                  </p>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
                  <label class="form-check-label" for="inlineCheckbox1">Держите меня в курсе новостей и эксклюзивных предложений</label>
                </div>
                
                <form action='{% url "orders:create_order" %}' method='post'>
                  {% csrf_token %}
                <div class="edit-checkout-form">
                  <h4 class="title">Адрес доставки</h4>
                  <div class="row row-gutter-12">

                    <div class="col-lg-6">
                      <div class="form-floating">
                        <label for="id_first_name">Имя*</label>
                        <input type="text" class="form-control" id="id_first_name" 
                        placeholder="name", value="{% if form.first_name.value %}
                        <p>{{form.first_name.value}}</p>
                        {% endif %}"
                        name='first_name' required>
                        {% if form.first_name.errors %}
											  <p>{{form.first_name.errors}}</p>
											  {% endif %}
                      </div>
                    </div>

                    <div class="col-lg-6">
                      <div class="form-floating">
                        <label for="id_last_name">Фамилия*</label>
                        <input type="text" class="form-control" 
                        id="id_last_name" placeholder="name" name='last_name' 
                        value="{% if form.last_name.value %}
                        <p>{{form.last_name.value}}</p>
                        {% endif %}" required>
                        {% if form.last_name.errors %}
											    <p>{{form.last_name.errors}}</p>
											  {% endif %}
                      </div>
                    </div>

                    <div class="col-lg-12">
                      <div class="form-floating">
                        <label for="id_phone_number" class="form-label" >Номер телефона*</label>
                        <input type="text" class="form-control" id="id_phone_number" 
                        placeholder="В формате XXX-XXX-XX-XX" name='phone_number' 
                        value="{% if form.phone_number.value %}
                        <p>{{form.phone_number.value}}</p>
                        {% endif %}" required>
                    
                      </div>  
                      {% if form.phone_number.errors %}
											    <p>{{form.phone_number.errors}}</p>
											  {% endif %}
                    </div>


                    <div class="col-lg-12">
                      <label for='delivery' class='form-label'>Способ доставки:</label>
                    </div>
  
                      <div class="col-lg-6">
                        <div class="form-check form-checkbox">
                          <label class="form-check-label" for="id_requires_delivery">Нужна доставка</label>
                          <input class="form-check-input" type="checkbox" 
                          name='requires_delivery' id="id_requires_delivery" value="1" checked>
                        </div>
                        <div class="form-check form-checkbox">
                          <input class="form-check-input" type="checkbox" name='requires_delivery' id="id_requires_delivery" value="0" >
                          <label class="form-check-label" for="id_requires_delivery">Самовывоз</label>
                        </div>
                      </div>
                    

                    <div class="col-lg-12">
                      <div class="form-floating">
                        <textarea type="text"  id="id_delivery_adress" 
                        name="delivery_adress" value="{% if form.delivery_adress.value %}
                        <p>{{form.delivery_adress.value}}</p>
                        {% endif %}" rows="2"></textarea> 
                        <label for="id_delivery_adress">Адрес*</label>
                      </div>
                      {% if form.delivery_adress.errors %}
                      <p>{{form.delivery_adress.errors}}</p>
                    {% endif %}
                    </div>

                    {% comment %} <div class="col-lg-12">
                      <div class="form-floating">
                        <input type="text" class="form-control" id="floatingInput4Grid" placeholder="address" value="">
                        <label for="floatingInput4Grid">Улица</label>
                      </div>
                    </div>

                    <div class="col-lg-12">
                      <div class="form-floating">
                        <input type="text" class="form-control" id="floatingInput5Grid" placeholder="address" value="">
                        <label for="floatingInput5Grid">Квартира, дом</label>
                      </div>
                    </div> {% endcomment %}

                    {% comment %} <div class="col-lg-6">
                      <div class="form-floating">
                        <select class="form-select form-control" id="floatingInput6rid" aria-label="Floating label select example">
                          <option selected>Bangladesh</option>
                          <option value="1">Afghanistan</option>
                          <option value="2">Åland Islands</option>
                          <option value="3">Albania</option>
                        </select>
                        <div class="field-caret"></div>
                        <label for="floatingInput6rid">Country/Region</label>
                      </div>
                    </div> {% endcomment %}

                    {% comment %} <div class="col-lg-6">
                      <div class="form-floating">
                        <input type="text" class="form-control" id="floatingInput7Grid" placeholder="address" value="">
                        <label for="floatingInput7Grid">Почтовый код</label>
                      </div>
                    </div> {% endcomment %}

                    <div class="col-lg-12">
                      <label for='delivery' class='form-label'>Способ оплаты: </label>
                    </div>
  
                      <div class="col-md-12 md-3">

                        <div class="form-check form-checkbox">
                          <label class="form-check-label"  for="id_payment_on_get">Оплата картой</label>
                          <input class="form-check-input" type="checkbox" 
                          name='payment_on_get' id="id_payment_on_get" value="0" checked>
                        </div>

                        <div class="form-check form-checkbox">
                          <input class="form-check-input" type="checkbox" name='payment_on_get'
                           id="id_payment_on_get" value="1" >
                          <label class="form-check-label" for="id_payment_on_get">При получении</label>
                        </div>
                        {% if form.payment_on_get.errors %}
											    <p>{{form.payment_on_get.errors}}</p>
											  {% endif %}

                      </div>


                    


                    <div class="col-12">
                      <div class="btn-box">
                        {% comment %} <button class="btn-shipping" href="{% url "orders:create_order" %}">Продолжит</button> {% endcomment %}
                        <button class="btn btn-outline" type="submit">Продолжит</button>
                        <a class="btn-return" href="{% url 'catalog:index'  'all' %}">Вернуться в корзину</a>
                      </div>
                    </div>
                  </form>

                  </div>
                </div>
              </div>
            </div>

            
            <div class="col-lg-5">
              <div class="shipping-cart-subtotal-wrapper">
                <div class="shipping-cart-subtotal">

                  {% for cart in carts %}
                  <div class="shipping-cart-item">
                    <div class="thumb">
                      <img src="{{cart.product.images.url}}" alt="Товар" >
                      <span class="quantity">{{cart.quantity}}</span>
                    </div>
                    <div class="content">
                      <h4 class="title">Meta Slevless Dress</h4>
                      <span class="info">s / purple / metal</span>
                      <span class="price">{{cart.products_price}}</span>
                    </div>
                  </div>
                  {% endfor %}
                  
                  <div class="shipping-subtotal">
                    <p><span>Промежуточный итог</span><span><strong>{{carts.total_price}}</strong></span></p>
                    <p><span>Доставка</span><span>Рассчитывается на следующем этапе</span></p>
                  </div>

                  <div class="shipping-total">
                    <p class="total">Итого</p>
                    <p class="price"><span class="usd">Rub</span>{{carts.total_price}}</p>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--== End Product Area Wrapper ==-->
    <div class="edit-checkout-footer">
      <p>Все права защищены. Rossalia.</p>
    </div>
  </main>

  <!--== Scroll Top Button ==-->
  <div id="scroll-to-top" class="scroll-to-top"><span class="fa fa-angle-double-up"></span></div>

  <!--== Start Quick View Menu ==-->
  <aside class="product-quick-view-modal">
    <div class="product-quick-view-inner">
      <div class="product-quick-view-content">
        <button type="button" class="btn-close">
          <span class="close-icon"><i class="fa fa-close"></i></span>
        </button>
        <div class="row">
          <div class="col-lg-6 col-md-6 col-12">
            <div class="thumb">
              <img src="assets/img/shop/quick-view1.jpg" alt="Alan-Shop">
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-12">
            <div class="content">
              <h4 class="title">Meta Slevless Dress</h4>
              <div class="prices">
                <del class="price-old">$85.00</del>
                <span class="price">$70.00</span>
              </div>
              <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,</p>
              <div class="quick-view-select">
                <div class="quick-view-select-item">
                  <label for="forSizes" class="form-label">Size:</label>
                  <select class="form-select" id="forSizes" required>
                    <option selected value="">s</option>
                    <option>m</option>
                    <option>l</option>
                    <option>xl</option>
                  </select>
                </div>
                <div class="quick-view-select-item">
                  <label for="forColors" class="form-label">Color:</label>
                  <select class="form-select" id="forColors" required>
                    <option selected value="">red</option>
                    <option>green</option>
                    <option>blue</option>
                    <option>yellow</option>
                    <option>white</option>
                  </select>
                </div>
              </div>
              <div class="action-top">
                <div class="pro-qty">
                  <input type="text" id="quantity4" title="Quantity" value="1" />
                </div>
                <button class="btn btn-black">Add to cart</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="canvas-overlay"></div>
  </aside>
  <!--== End Quick View Menu ==-->

</div>
</body>

</html>