appShop/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]


if settings.DEBUG:
    urlpatterns += [
    path("__debug__/", include("debug_toolbar.urls")),
    ]   
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appShop/carts/urls.py
from django.urls import path

from carts import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/<slug:product_slug>/', views.cart_add, name='cart_add'),
    path('cart_change/<slug:product_slug>/', views.cart_change, name='cart_change'),
    path('cart_remove/<int:cart_id>/', views.cart_remove, name='cart_remove'),
]

appShop/main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

appShop/orders/urls.py
from django.urls import path
from orders import views


app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
]

appShop/carts/models.py
from django.db import models

from goods.models import Products
from users.models import User

# Create your models here.

class CartQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количесво')
    session_key = models.CharField(max_length=32, blank=True, null=True)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = "cart"
        verbose_name= "Корзина"
        verbose_name_plural= "Корзина"

    objects = CartQueryset().as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        if self.user:
            return f"Корзина {self.user.username} | Товар {self.product.name} | Количесво {self.quantity}"
        
        return f"Анонимная корзина | Товар {self.product.name} | Количесво {self.quantity}"

appShop/carts/views.py
from django.shortcuts import redirect, render
from goods.models import Products
from carts.models import Cart
# Create your views here.

def cart_add(request, product_slug):
    product = Products.objects.get(slug=product_slug)

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity+= 1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity=1)
    
    else:
        carts = Cart.objects.filter(session_key=request.session.session_key, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity+= 1
                cart.save()
        else:
            Cart.objects.create(session_key=request.session.session_key, 
                                product=product, quantity=1)

    return redirect(request.META['HTTP_REFERER'])

def cart_change(request, product_id):
    pass


def cart_remove(request, cart_id):
    
    cart = Cart.objects.get(id=cart_id)
    cart.delete()
    return redirect(request.META['HTTP_REFERER'])

appShop/carts/templates/carts/includes/included_carts.html
{% load static %}	
{% load carts_tags %}						
							
{%user_carts request as carts%}



			{% if carts %}
			<form>
				<table class="table shop_table cart">
					<thead>
						<tr>
							<th class="product-remove hidden-xs">&nbsp;</th>
							<th class="product-thumbnail hidden-xs">&nbsp;</th>
							<th class="product-name">Product</th>
							<th class="product-price text-center">Price</th>
							<th class="product-quantity text-center">Quantity</th>
							<th class="product-subtotal text-center hidden-xs">Total</th>
						</tr>
					</thead>
				
					{% for cart in carts %}
					<tbody>
						<tr class="cart_item">
							<td class="product-remove hidden-xs">
								<a href="{% url "cart:cart_remove" cart.id %}" class="remove" title="Remove this item">&times;</a>
							</td>
							<td class="product-thumbnail hidden-xs">
								<a href="shop-detail-1.html">
									<img width="100" height="150" src="{{cart.product.images.url}}" alt="Product-2"/>
								</a>
							</td>
							
							<td class="product-name">
								<a href="shop-detail-1.html">{{cart.product.name}}</a>
								<dl class="variation">
									<dt class="variation-Color">Color:</dt>
									<dd class="variation-Color"><p>Green</p></dd>
									<dt class="variation-Size">Size:</dt>
									<dd class="variation-Size"><p>Medium</p></dd>
								</dl>
							</td>
							<td class="product-price text-center">
								<span class="amount">&#36;{{cart.product.sell_price}}</span>
							</td>
							<td class="product-quantity text-center">
								<div class="quantity">
									<input type="number" step="1" min="0" name="quantity" value="{{cart.quantity}}" title="Qty" class="input-text qty text" size="4"/>
								</div>
							</td>
							<td class="product-subtotal hidden-xs text-center">
								<span class="amount">&#36;{{cart.products_price}}</span>
							</td>
						</tr>
					</tbody>
					{% endfor %}


				</table>
			</form>
			<div class="cart-collaterals">
				<div class="cart_totals">
					<h2>Cart Totals</h2>
					<table>
						<tr class="cart-subtotal">
							<th>Промежуточный итог</th>
							<td><span class="amount">&#36;{{carts.total_price}}</span></td>
						</tr>
						<tr class="shipping">
							<th>Доставка</th>
							<td><span class="amount">&#36;0.00</span></td>
						</tr>
						<tr class="order-total">
							<th>Сумма</th>
							<td><strong><span class="amount">&#36;{{carts.total_price}}</span></strong></td>
						</tr>
					</table>
					
					<div class="wc-proceed-to-checkout">
						<a href="{% url "orders:create_order" %}" class="checkout-button button alt wc-forward">ПЕРЕЙТИ К ОФОРМЛЕНИЮ ЗАКАЗА</a>
					</div>
				</div>
					</ul>
				</div>
			</div>



			{% else %}


			<div class="content-container">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="main-content">
								<div class="commerce">
									<p class="cart-empty">Ваша корзина на данный момент пуста</p>
									<p class="return-to-shop"><a class="button wc-backward" href="{% url "catalog:index" "all" %}">Вернуться в магазин</a></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>


			{% endif %}