appShop/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]


if settings.DEBUG:
    urlpatterns += [
    path("__debug__/", include("debug_toolbar.urls")),
    ]   
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appShop/goods/urls.py
from django.urls import path

from goods import views

app_name = 'catalog'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

appShop/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('users_card/', views.users_card, name='users_card'),
]

appShop/orders/models.py
from django.db import models
from users.models import User
from goods.models import Products
# Create your models here.

class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0




class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, verbose_name="Пользователь", blank=True, null=True, default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    requires_delivery = models.BooleanField(default=False, verbose_name='Требуется доставка')
    delivery_adress = models.TextField(null=True, blank=True, verbose_name='Адрес доставки')
    payment_on_get = models.BooleanField(default=False, verbose_name='Оплата при получении')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    status = models.CharField(max_length=50, default='В обработке', verbose_name='Статус заказа')

    class Meta:
        db_table = 'order'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
    
    def __str__(self):
        return f"Заказ № {self.pk} | Покупятеля {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, verbose_name='Продукт', null=True, default=None)
    name = models.CharField(max_length=150, verbose_name='Название')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')

    class Meta:
        db_table = "order_item"
        verbose_name = 'Проданный товар'
        verbose_name_plural = 'Проданные товвары'

    objects = OrderitemQueryset.as_manager()

    def product_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f'Товар {self.name} | Заказ № {self.order.pk}'        

appShop/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='user_imges', blank=True, null=True, verbose_name="Аватар")
    phone_number = models.CharField(max_length=14, verbose_name="Номер телефона",  blank=True, null=True)


    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

appShop/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from users.models import User

class UserLoginForm(AuthenticationForm):

    username = forms.CharField()
    password = forms.CharField()
    class Meta:
        model = User

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    

appShop/users/views.py
from django.shortcuts import redirect, render
from orders.models import Order, OrderItem
from carts.models import Cart
from users.forms import UserLoginForm, UserRegistrationForm
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch


def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                return HttpResponseRedirect(reverse('main:index'))

    else:
        form = UserLoginForm()

    context = {
        'title': 'Авторизация',
        'form': form
    }
    return render(request, 'users/login.html', context)

def registration(request):

    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
                form.save()

                session_key = request.session.session_key   

                user = form.instance
                auth.login(request, user)
                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Регистрация',
        'form':form
    }
    return render(request, 'users/registration.html', context)



@login_required
def profile(request):

    orders = (
        Order.objects.filter(user=request.user).prefetch_related(Prefetch("orderitem_set",
                                                                queryset=OrderItem.objects.select_related('product'),
                                                                )).order_by('-id')
            )

    context = {
        'title': 'Профиль',
        'orders': orders
    }
    return render(request, 'users/profile.html', context)




def logout(request):
    auth.logout(request)
    return redirect(reverse('main:index'))


def users_card(request):
    return render(request, 'users/users_card.html')

appShop/users/templates/users/login.html
{% extends "base.html" %}

{% load static %}


{% block content %}
		 	 <div class="heading-container">
				<div class="container heading-standar">
					<div class="page-breadcrumb">
						<ul class="breadcrumb">
							{% comment %} <li>
								<span>
									<a class="home" href="#">
										<span>Home</span>
									</a>
								</span>
							</li>
							<li>
								<span>My Account</span>
							</li> {% endcomment %}
						</ul>
					</div>
				</div>
			</div>  
			<div class="content-container no-padding">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="main-content">
								<div class="commerce commerce-account">
									<h2 class="commerce-account-heading">Вход</h2>



									<form class="login" action="{% url "user:login" %}" method="post">
										{% csrf_token %}
									
										

									<div class="form-row form-row-wide">
											<label for="id_username">
												Введите ваше имя <span class="required">*</span>
											</label>
											<input type="text" class="input-text" name="username" value="{% if form.username.value %}{{form.username.value}}{% endif %}" id="id_username" placeholder="Введите ваше имя пользователя" value=""/>
										</div>
										<div class="form-row form-row-wide">
											<label for="id_password">Введите ваш пароль <span class="required">*</span></label>
											<input class="input-text" type="password" name="password" id="id_password" placeholder="Введите ваш пароль пользователя"/>
										</div>
										<div class="form-row">
											 <label for="rememberme1" class="inline form-flat-checkbox">
												<input name="rememberme" type="checkbox" id="rememberme1" value="forever"/><i></i>Remember me 
											</label> 
											<br><br>
											<button class="btn btn-outline" type="submit">Войти</button>
										</div>

								

										<div class="lost_password">
											<a href="#">Забыл пароль?</a>
										</div>
										<div class="lost_password">
											<a href="{% url "user:registration" %}">Регистрация</a>
										</div> 
									</form>




								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endblock  %}

appShop/users/templates/users/profile.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="https://bootstraptema.ru/plugins/2015/bootstrap3/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<script src="https://bootstraptema.ru/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="https://bootstraptema.ru/plugins/2015/b-v3-3-6/bootstrap.min.js"></script>
<link rel='stylesheet' href="{% static 'css/customProfil.css' %}" type='text/css' media='all'/>
{% endblock  %}

{% block content %}
			 

<br><br><br>



<div class="container">
<div id="main">


 <div class="row" id="real-estates-detail">
 <div class="col-lg-4 col-md-4 col-xs-12">
 <div class="panel panel-default">
 <div class="panel-heading">
 <header class="panel-title">
 <div class="text-center">
 <strong>Пользователь сайта</strong>
 </div>
 </header>
 </div>
 <div class="panel-body">
 <div class="text-center" id="author">
 <img src="{% static "images/userlogo.jpg" %}">
 <h3>Василий Понторезов</h3>
 <small class="label label-warning">Российская Федерация</small>
 <p>Я простой Русский пацан и мне всё по барабану.</p>
 <p class="sosmed-author">
 <a href="#"><i class="fa fa-facebook" title="Facebook"></i></a>
 <a href="#"><i class="fa fa-twitter" title="Twitter"></i></a>
 <a href="#"><i class="fa fa-google-plus" title="Google Plus"></i></a>
 <a href="#"><i class="fa fa-linkedin" title="Linkedin"></i></a>
 </p>
 </div>
 </div>
 </div>
 </div>


 <div class="col-lg-8 col-md-8 col-xs-12">
 <div class="panel">
 <div class="panel-body">
 <ul id="myTab"  class="nav nav-pills">
 	<li class="active"><a href="#detail"  data-toggle="tab">О пользователе</a></li>
 	<li class=""><a href="#order"  data-toggle="tab">Мои заказы</a></li>
 	<li class=""><a href="#contact" data-toggle="tab">Отправить сообщение</a></li>
 </ul>



 <div id="myTabContent" class="tab-content">
<hr>
 <div class="tab-pane fade active in" id="detail">
 <h4>История профиля</h4>
 <table class="table table-th-block">
 <tbody>
 <tr><td class="active">Зарегистрирован:</td><td>12-06-2016</td></tr>
 <tr><td class="active">Последняя активность:</td><td>12-06-2016 / 09:11</td></tr>
 <tr><td class="active">Страна:</td><td>Россия</td></tr>
 <tr><td class="active">Город:</td><td>Волгоград</td></tr>
 <tr><td class="active">Пол:</td><td>Мужской</td></tr>
 <tr><td class="active">Полных лет:</td><td>43</td></tr>
 <tr><td class="active">Семейное положение:</td><td>Женат</td></tr>
 <tr><td class="active">Рейтинг пользователя:</td><td><i class="fa fa-star" style="color:red"></i> <i class="fa fa-star" style="color:red"></i> <i class="fa fa-star" style="color:red"></i> <i class="fa fa-star" style="color:red"></i> 4/5</td></tr>
 <tr><td class="active">Плагин рейтинга:</td><td><a href="https://bootstraptema.ru/stuff/plugins_bootstrap/improvement/bootstrap_star_rating/12-1-0-73" target="_blank">http://goo.gl/bGGXuw</a></td></tr>
</tbody>
 </table>
 </div>






	
<div class="tab-pane fade" id="order">
		
	 <table class="table table-th-block">
		
	 <tbody>

		<div class="container">
			<div class="row">
			  <div class="col-lg-12">
				<h2>Мои заказы</h2>
				{% for order in orders %}
				<h4>
				  <a class="btn-label" data-toggle="collapse{{order.id}}" href="#hiddenText{{order.id}}" role="button" aria-expanded="false" aria-controls="hiddenText">
					↓ Заказ {{order.id}} - {{order.created_timestamp}} | Статус: {{order.status}}
				  </a>
				</h4>

				<div class="collapse{{order.id}}" id="hiddenText{{order.id}}">
					<tbody>
						{% for item in order.orderitem_set.all %}
						<tr>
							<td><a class="text-white" href="{% url 'catalog:product' item.product.slug %}">{{ item.product.name }}</a></td>
							<td>{{ item.quantity }}</td>
							<td>{{ item.price }}</td>
							<td>{{ item.products_price }}</td>
							
						</tr>
						{% endfor %}
					</tbody>
				</div>
				{% endfor %}
			  </div>
			</div>
		  </div>
	</div>

	</tbody>
	</table>
	</div> 








 <div class="tab-pane fade" id="contact">
 <p></p>
 <form role="form">
 <div class="form-group">
 <label>Ваше имя</label>
 <input type="text" class="form-control rounded" placeholder="Укажите Ваше Имя">
 </div>
 <div class="form-group">
 <label>Ваш телефон</label>
 <input type="text" class="form-control rounded" placeholder="(+7)(095)123456">
 </div>
 <div class="form-group">
 <label>E-mail адрес</label>
 <input type="email" class="form-control rounded" placeholder="Ваш Е-майл">
 </div>
 <div class="form-group">
 <div class="checkbox">
 <label>
 <input type="checkbox"> Согласен с условиями
 </label>
 </div>
 </div>
 <div class="form-group">
 <label>Текст Вашего сообщения</label>
 <textarea class="form-control rounded" style="height: 100px;"></textarea>
 <p class="help-block">Текст сообщения будет отправлен пользователю</p>
 </div>
 <div class="form-group">
 <button type="submit" class="btn btn-success" data-original-title="" title="">Отправить</button>
 </div>
 </form>
 </div>



 </div>
 </div>
 </div>
 </div>
 </div>
</div>

	</div><!-- /.main -->
</div><!-- /.container -->

{% endblock  %}		

appShop/users/templates/users/registration.html
{% extends "base.html" %}

{% load static %}


{% block content %}
		 	<div class="heading-container">
				<div class="container heading-standar">
					<div class="page-breadcrumb">
						<ul class="breadcrumb">
							{% comment %} <li>
								<span>
									<a class="home" href="#">
										<span>Home</span>
									</a>
								</span>
							</li>
							<li>
								<span>My Account</span>
							</li> {% endcomment %}
						</ul>
					</div>
				</div>
			</div> 
			<div class="content-container no-padding">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="main-content">
								<div class="commerce commerce-account">
									<h2 class="commerce-account-heading">Регистрация</h2>



									<form class="login" action="{% url "user:registration" %}" method="post">
										{% csrf_token %}
									
										

									<div class="form-row form-row-wide">
											<label for="id_first_name">
												Введите имя <span class="required">*</span>
											</label>
											<input type="text" class="input-text" name="first_name" 
											value="{% if form.first_name.value %}{{form.first_name.value}}{% endif %}" 
											id="id_first_name" placeholder="Введите ваше имя" value=""/>
											{% if form.first_name.errors %}
											<p>{{form.first_name.errors}}</p>
											{% endif %}
									</div>

									<div class="form-row form-row-wide">
										<label for="id_last_name">
											Введите фамилию <span class="required">*</span>
										</label>
										<input type="text" class="input-text" name="last_name" 
										value="{% if form.last_name.value %}{{form.last_name.value}}{% endif %}" 
										id="id_last_name" placeholder="Введите вашу фамилию" value=""/>
										{% if form.last_name.errors %}
											<p>{{form.last_name.errors}}</p>
											{% endif %}
									</div>	

									<div class="form-row form-row-wide">
											<label for="id_username">
												Введите имя пользователя <span class="required">*</span>
											</label>
											<input type="text" class="input-text" name="username" 
											value="{% if form.username.value %}{{form.username.value}}{% endif %}" 
											id="id_username" placeholder="Введите имя пользователя" value=""/>
											{% if form.username.errors %}
											<p>{{form.username.errors}}</p>
											{% endif %}
									</div>

									<div class="form-row form-row-wide">
										<label for="id_email">Введите email<span class="required">*</span></label>
										<input class="input-text" type="email" name="email" 
										id="id_email" placeholder="Введите ваш email"/>
										{% if form.email.errors %}
											<div>{{form.email.errors}}</div>
										{% endif %}
									</div>

									<div class="form-row form-row-wide">
										<label for="id_password1">Введите пароль<span class="required">*</span></label>
										<input class="input-text" type="password" name="password1" 
										id="id_password1" placeholder="Введите пароль"/>
										{% if form.password1.errors %}
											<p>{{form.password1.errors}}</p>
										{% endif %}
									</div>

									<div class="form-row form-row-wide">
										<label for="id_password2">Подтвердите пароль<span class="required">*</span></label>
										<input class="input-text" type="password" name="password2" 
										id="id_password2" placeholder="Подтвердите пароль"/>
										{% if form.password2.errors %}
											<p>{{form.password2.errors}}</p>
										{% endif %}
									</div>


										<div class="form-row">
											 <label for="rememberme1" class="inline form-flat-checkbox">
												<input name="rememberme" type="checkbox" id="rememberme1" value="forever"/><i></i>Remember me 
											</label> 
											<br><br>
											<button class="btn btn-outline" type="submit">Зарегистрироватся</button>
										</div>

								

										<div class="lost_password">
											<a href="#">Забыл пароль?</a>
										</div>
										<div class="lost_password">
											<a href="{% url "user:login" %}">Войти</a>
										</div> 
									</form>




								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endblock  %}


			{% comment %} <div class="d-flex align-items-center">
				<div class="p-2">Flex item 1</div>
				<div class="p-2">Flex item 2</div>
				<div class="p-2">Flex item 3</div>
			  </div>
			  
			  <!-- responsive variations -->
			  <div class="d-flex align-items-sm-center">...</div>
			  <div class="d-flex align-items-md-center">...</div>
			  <div class="d-flex align-items-lg-center">...</div>
			  <div class="d-flex align-items-xl-center">...</div> {% endcomment %}
			  

appShop/users/templates/users/users_card.html
{% extends "base.html" %} 
{% load static %}

{% block content %}

			<div class="heading-container">
				<div class="container heading-standar">
					<div class="page-breadcrumb">
						<ul class="breadcrumb">
							
						</ul>
					</div>
				</div>
			</div>
			<div class="content-container">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="main-content">
								<div class="commerce">
									

                                    {% include "carts/includes/included_carts.html" %}

								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endblock  %} 