appShop/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]


if settings.DEBUG:
    urlpatterns += [
    path("__debug__/", include("debug_toolbar.urls")),
    ]   
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appShop/carts/urls.py
from django.urls import path

from carts import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/<slug:product_slug>/', views.cart_add, name='cart_add'),
    path('cart_change/<slug:product_slug>/', views.cart_change, name='cart_change'),
    path('cart_remove/<int:cart_id>/', views.cart_remove, name='cart_remove'),
]

appShop/goods/urls.py
from django.urls import path

from goods import views

app_name = 'catalog'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

appShop/goods/models.py
from django.urls import reverse
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

class Products(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    images = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta: 
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f'{self.name} Количество - {self.quantity}'
    
    def display_id(self):
        return f'{self.id:04}'
    
    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})
    
    
    def sell_price(self):
        if self.discount:
            return round(self.price - (self.price*self.discount/100), 2)
        
        return self.price

appShop/goods/views.py
from django.shortcuts import get_list_or_404, render
from goods.utils import q_serch
from goods.models import Products
from django.core.paginator import Paginator


def catalog(request, category_slug=None):

    page = request.GET.get('page', 1)
    query = request.GET.get('q', None)
    

    if category_slug == "all":
        goods = Products.objects.all()
    elif query:
        goods = q_serch(query)
        
    else:
        goods = get_list_or_404(Products.objects.filter(category__slug=category_slug))

    paginator = Paginator(goods, 3)

    current_page = paginator.page(int(page))

    context ={ 
        "title" : "Каталог",
        "goods" : current_page,
    }
    return render(request, 'goods/catalog.html', context)

def product(request, product_slug):

    product = Products.objects.get(slug=product_slug)

    goods = Products.objects.all()

    paginator = Paginator(goods, 3)
    current_page = paginator.page(1)

    context ={ 
        "title" : "Каталог",
        "product" : product,
         "goods" : current_page,
    }
    return render(request, 'goods/product.html', context)

appShop/goods/templates/goods/catalog.html
{% extends "base.html" %} 
{% load static %}

{% block content %}
<div class="heading-container">
				<div class="container heading-standar">
					<div class="page-breadcrumb">
						<ul class="breadcrumb">
							{% comment %} <li>
								<span>
									<a class="home" href="{% url "main:index" %}">
										<span>Главная</span>
									</a>
								</span>
							</li>
							<li>
								<span>Каталог</span>
							</li> {% endcomment %}
						</ul>
					</div>
				</div>
			</div>
			<div class="content-container">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="main-content">
								<div class="commerce columns-3">
									<ul class="products columns-3" data-columns="3">

										{%if request.GET.q%}
										<h3 class="mt-4">Результат поиска по запросу {{request.GET.q}}</h3>
										{% comment %} {%if not goods%}
										<h2 class='mt-4'>По запосу ничего не найдено</h2>
										{% endif %} {% endcomment %}
										{% endif %}

										{% for product in goods %}

										<li class="product col-md-3 col-sm-6">
											<div class="product-container">
												<figure>
													<div class="product-wrap">
														<div class="product-images">

															{% if  product.images %}
															<div class="shop-loop-thumbnail shop-loop-front-thumbnail">
																<img width="375" height="505" src="{{product.images.url}}" alt="{{product.name}}"/>
															</div>
															<div class="shop-loop-thumbnail shop-loop-back-thumbnail">
																<img width="375" height="505" src="{{product.images.url}}" alt="{{product.name}}"/>
															</div>
															{% else %}
															
																<div class="shop-loop-thumbnail shop-loop-front-thumbnail">
																	<img width="375" height="505" src="{% static "вставить ссылку на картинку когда нет фото" %}" alt="{{product.name}}"/>
																</div>
																<div class="shop-loop-thumbnail shop-loop-back-thumbnail">
																	<img width="375" height="505" src="{% static "вставить ссылку на картинку когда нет фото" %}" alt="{{product.name}}"/>
																</div>
															{% endif %}

															<div class="loop-action">
																<div class="shop-loop-quickview">
																	<a title="Quick view" href="{% url "catalog:product" product.slug%}">
																		Описание
																	</a>
																</div>
																<div class="loop-add-to-cart">
																	<a href="{% url "cart:cart_add" product.slug%}" class="add_to_cart_button">
																		Добавить в корзину
																	</a>
																</div>
															</div>
														</div>
													</div>
													<figcaption>
														<div class="shop-loop-product-info">
															<div class="info-meta clearfix">
																
																 <div class="container">
																	<p class="text-white bg-dark font-weight-light font-italic">{{product.display_id}}</p>
																</div> 
																{% comment %} <div class="loop-add-to-wishlist">
																	<div class="yith-wcwl-add-to-wishlist">
                                                                        <div class="yith-wcwl-add-button">
                                                                            <a href="#" class="add_to_wishlist">
                                                                                Add to Wishlist
                                                                            </a>
                                                                        </div>
                                                                    </div>
                                                                </div> {% endcomment %}
															</div>   
															<div class="info-content-wrap">
																<h3 class="product_title">
																	<a href="{% url "catalog:product" product.slug%}">{{product.name}}</a>
																</h3>

																{% if product.discount %}
																<div class="info-price">
																	<span class="price">
																		<span class="amount">
																			{{product.sell_price}} руб.
																		</span>
																		{% comment %} &ndash; {% endcomment %}
																		{% comment %} <span class="amount">
																			&pound;{{product.price}}
																		</span> {% endcomment %}
																	</span>
																{%else%}
																<div class="info-price">
																	<span class="price">
																		<span class="amount">
																			{{product.price}} руб.
																		</span>
																		{% comment %} &ndash; {% endcomment %}
																		{% comment %} <span class="amount">
																			&pound;{{product.price}}
																		</span> {% endcomment %}
																	</span>
																{% endif %}
															
															</div>
														</div>
													</figcaption>
												</figure>
											</div>
										</li>
										{% endfor %}

										
										
										<div class="paginate">
											<div class="paginate_links">

												{% comment %} <span class='page-numbers current'>1</span> {% endcomment %}
												<a class="prev page-numbers disabled" href="{% if goods.has_previous %}
												?page={{goods.previous_page_number}}
												{% else %}
												#
												{% endif %}">
													<i class="fa fa-angle-left"></i>
												</a>

												{% for page in goods.paginator.page_range %}
												<a class='page-numbers {% if goods.number == page %}active{% endif %}' href='?page={{page}}'>{{ page }}</a>
											
												{% endfor %}

												<a class="next page-numbers" href="{% if goods.has_next %}?page={{goods.next_page_number}}
												{% else %}
												#
												{% endif %}">
													<i class="fa fa-angle-right"></i>
												</a>
												
											</div>
										</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
	
		{% endblock  %} 